name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)

# Trigger on the master and the release-1.4 branches only
# Stndard Pull Request and Merge builds
# Any git tag will also trigger a build that should do publishing
trigger:
  branches:
    include:
      - 'master'

  tags:
    include:
      - '*'

# Build on Ubuntu
pool:
  vmImage: 'ubuntu-latest'

# 
# The stages and jobs, potential for rationalization and optimization
# Keeping it simple and explict whilst we gain experience
stages:

    # output some basic information for reference
    # Not for use every time, but this can be useful template to keep
    # - stage: info
    #   jobs:
    #     - job: env_info
    #       steps:
    #         - script: |
    #             env | sort      

    # Primary stage of building, linting and unit tests
    - stage: Build_and_Test
      jobs:
        - job: main
          displayName: 'Build, lint, UT'
          steps:
            - task: NodeTool@0
              inputs:
                versionSpec: '10.x' 
            - script: |
                set -ev
                node common/scripts/install-run-rush.js install
              displayName: 'Setup the rush environment'
            - script: |
                set -ev 
                node common/scripts/install-run-rush.js rebuild
              displayName: 'Full rebuild'
            - script: |
                set -ev
                node common/scripts/install-run-rush.js publish --include-all --pack --release-folder $(Build.ArtifactStagingDirectory)/tgz --publish   
            - task: PublishBuildArtifacts@1    
              inputs:
                pathToPublish:  $(Build.ArtifactStagingDirectory)/tgz
                artifactName: node-tgz 